name: gojek_ui
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  flutter_gen: ^5.1.0+1
  flutter_svg: ^1.1.6
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# Generate shared resource image, color and font
# For Generate command at terminal 'fluttergen -c pubspec.yaml'
flutter_gen:
  output: lib/resources
  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: true
      style: snake-case

  # integrations:
  #   flutter_svg: true

  colors: 
    inputs:
      - assets/color/main_color.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF